[package]
name = "image_sieve"
version = "0.3.3"
authors = ["Florian Fetz <florian.fetz@googlemail.com>"]
description = "GUI based tool to sort out and categorize images with the help of image similarity classification"
repository = "https://github.com/Futsch1/image-sieve"
license = "GPL-3.0+"
categories = ["multimedia::images"]
build = "build.rs"
edition = "2021"
readme = "README.md"

[dependencies]
sixtyfps = "0.1.5"
rfd = "^0.6"
image = "^0.23.14"
kamadak-exif = "^0.5"
chrono = "^0.4"
num-traits = "^0.2"
num-derive = "^0.3"  
opener = "^0.5"
img_hash = "^3.2"
serde = "^1.0"
serde_json = "^1.0"
serde_with = "^1.0"
home = "^0.5"
walkdir = "2"

[dev-dependencies]
base64 = "^0.13"

[build-dependencies]
sixtyfps-build = "0.1.5"
winres = "^0.1"
