[package]
name = "image_sieve"
version = "0.1.3"
authors = ["Florian Fetz <florian.fetz@googlemail.com>"]
description = "GUI based tool to sort out and categorize images"
repository = "https://github.com/Futsch1/image-sieve"
license = "GPL-3.0"
categories = ["multimedia::images"]
build = "build.rs"
edition = "2018"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sixtyfps = "0.1.2"
rfd = "0.4.0"
json = "0.12"
image = "0.23"
glob = "0.3.0"
kamadak-exif = "0.5.4"
chrono = "0.4"
num-traits = "0.2"
num-derive = "0.3"
opener = "0.5.0"

[build-dependencies]
sixtyfps-build = "0.1.2"
embed-resource = "1.6"

[[bin]]
name = "image_sieve"
doc = false