name: image-sieve 
base: core20 
version: '0.2.5'
summary: GUI based tool to sort out images and archive them in a target folder 
description: |
  ImageSieve aims to help in the process of sorting through images taken by several 
  people with several devices and collect the images worth keeping in a folder structure 
  suitable for achiving or to eliminate potential duplicates or irrelevant images from a 
  folder structure. 

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode 

build-packages:
  - cmake
  - libxcb-shape0-dev 
  - libxcb-xfixes0-dev 
  - libxkbcommon-dev 
  - libpango1.0-dev 
  - libatk1.0-dev 
  - libgtk-3-dev

apps:
  image-sieve:
    command: bin/image_sieve
    extensions: [gnome-3-38]
    plugs:
      - home
      - desktop
      - desktop-legacy 

parts:
  image-sieve:
    plugin: rust
    source: .

  deps:
    plugin: nil
    stage-packages:
      - libxcb-shape0
