name: image-sieve 
title: ImageSieve
base: core22
summary: Tool to sort out images and archive them in a target folder 
description: |
  ImageSieve aims to help in the process of sorting through images taken by several 
  people with several devices and collect the images worth keeping in a folder structure 
  suitable for achiving or to eliminate potential duplicates or irrelevant images from a 
  folder structure. 
adopt-info: image-sieve
# source-code: https://github.com/Futsch1/image-sieve.git
license: GPL-3.0+

grade: stable
confinement: strict
icon: snap/gui/ImageSieve.png

apps:
  image-sieve:
    command: bin/image_sieve
    extensions: [gnome]
    plugs:
      - home
      - removable-media
      - network

parts:
  image-sieve:
    plugin: rust
    source: .
    override-pull: |
      craftctl default
      ver=""
      ver=$(git describe --tags --abbrev=0 | sed 's/v//') || true
      if [ -z $ver ]
      then ver="0.0.0" 
      fi
      craftctl set version=$ver
    build-packages:
      - cmake
      - git
      - libxcb-shape0-dev 
      - libxcb-xfixes0-dev 
      - libxkbcommon-dev
      - libgtk-3-dev
      - libfontconfig1-dev
      - libavcodec-dev 
      - libavformat-dev 
      - libavutil-dev
      - libswscale-dev
      - libclang-dev

  deps:
    plugin: nil
    stage-packages:
      - libxcb-shape0
      - libxcb-xfixes0
      - libavcodec58
      - libavformat58
      - libavutil56
      - libswscale5
      - libgtk-3-0
