import { Button, CheckBox, GroupBox, LineEdit, VerticalBox, ComboBox, HorizontalBox, AboutSlint } from "std-widgets.slint";

import { Palette } from "std-widgets-impl.slint";

export SettingsView := VerticalBox { 
    property use-timestamps <=> use-timestamps-checkbox.checked;
    property timestamp-difference <=> timestamp-difference-edit.text;
    property use-similarity <=> use-similarity-checkbox.checked;
    property similarity-sensitivity <=> sensitivity-combobox.current-value;
    property dark-mode <=> dark-mode.checked;

    callback recheck-similarities;
    callback open-url(string);
    callback apply-dark-mode();
    apply-dark-mode => { 
        if (dark-mode.checked) {
            Palette.white = #0d1117;
            Palette.black = #ffffff;
            Palette.neutralDark = #edebe9;
            Palette.neutralPrimary = #d2d0ce;
            Palette.neutralPrimaryAlt = #e1dfdd;
            Palette.neutralSecondary = #a19f9d;
            Palette.neutralSecondaryAlt = #c8c6c4;
            Palette.neutralTertiary = #605e5c;
            Palette.neutralTertiaryAlt = #8a8886;
            Palette.neutralQuaternary = #323130;
            Palette.neutralQuaternaryAlt = #3b3a39;
            Palette.neutralLight =  #3d3d3b;
            Palette.neutralLighter = #030201;
            Palette.themeDarker = #deecf9;
            Palette.themeDark = #c7e0f4;
            Palette.themeDarkAlt = #eff6fc;
            Palette.themePrimary = #71afe5;
            Palette.themeSecondary = #2b88d8;
            Palette.themeTertiary = #0078d4;
            Palette.themeLight = #005a9e;
            Palette.themeLighter = #004578;
            Palette.themeLighterAlt = #106ebe;
        } else {
            Palette.white = #ffffff;
            Palette.black = #000000;
            Palette.neutralDark = #201f1e;
            Palette.neutralPrimary = #323130;
            Palette.neutralPrimaryAlt = #3b3a39;
            Palette.neutralSecondary = #605e5c;
            Palette.neutralSecondaryAlt = #8a8886;
            Palette.neutralTertiary = #a19f9d;
            Palette.neutralTertiaryAlt = #c8c6c4;
            Palette.neutralQuaternary = #d2d0ce;
            Palette.neutralQuaternaryAlt = #e1dfdd;
            Palette.neutralLight = #edebe9;
            Palette.neutralLighter =  #f3f2f1;
            Palette.themeDarker = #004578;
            Palette.themeDark = #005a9e;
            Palette.themeDarkAlt = #106ebe;
            Palette.themePrimary = #0078d4;
            Palette.themeSecondary = #2b88d8;
            Palette.themeTertiary = #71afe5;
            Palette.themeLight = #c7e0f4;
            Palette.themeLighter = #deecf9;
            Palette.themeLighterAlt = #eff6fc;
        }
    }

    GroupBox { 
        title: "Similar pictures";

        VerticalBox { 
            alignment: start;

            HorizontalBox { 
                alignment: start;
                
                GridLayout {             
                    spacing: 5px;
                    use-timestamps-checkbox := CheckBox { 
                        text: "Use timestamps";
                        toggled => {
                            recheck-similarities();
                        }
                    }
                    Text {
                        text: "⇔ Maximum timestamp difference (s): ";                
                        vertical-alignment: center;
                        horizontal-alignment: right;
                        row: 2;
                    }
                    timestamp-difference-edit := LineEdit {
                        text: "5";
                        width: 50px;
                        enabled: use-timestamps-checkbox.checked;
                        accepted => { 
                            recheck-similarities();
                        }
                    }

                    use-similarity-checkbox := CheckBox { 
                        text: "Use image similarity";
                        toggled => {
                            recheck-similarities();
                        }
                        row: 4;
                    }
                    Text {
                        text: "Sensitivity: ";
                        vertical-alignment: center;
                        horizontal-alignment: right;
                        row: 5;
                    }
                    sensitivity-combobox := ComboBox {
                        model: ["Very low", "Low", "Medium", "High", "Very high"];
                        current-value: "Medium";                
                        enabled: use-similarity-checkbox.checked;
                        selected => { 
                            recheck-similarities();
                        }
                    }
                    Text {
                        text: "Dark mode: ";
                        vertical-alignment: center;
                        horizontal-alignment: right;
                        col: 0;
                        row: 6;
                    }
                    dark-mode := CheckBox {
                        text: "Dark mode";
                        toggled => { 
                            apply-dark-mode();
                        }
                    } 
                }
            }
        }            
    }
    HorizontalBox { 
        TouchArea { 
            VerticalBox {             
                alignment: start;
                HorizontalBox {                 
                    alignment: start;
                    Image {
                        source: @image-url("ImageSieve.png");
                    }
                }
                Text {
                    text: "💻 Developed by Florian Fetz";
                }
                Text {
                    text: "🔗 https://www.github.com/Futsch1/image-sieve";
                    color: blue;
                }
            }
            clicked => { 
                open-url("https://www.github.com/Futsch1/image-sieve");
            }
        }
        TouchArea { 
            width: 256px;
            height: 128px;
            AboutSlint {  }
            clicked => { 
                open-url("https://github.com/slint-ui/slint");
            }
        }
    }
    
}