name: Build

on: 
  push

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:    
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: C:\vcpkg\installed
        key: ${{ runner.os }}
    - name: Build release
      run: |
        vcpkg integrate install
        vcpkg install ffmpeg[avcodec,avformat,avdevice,swscale]:x64-windows-static libheif:x64-windows-static
        cargo build --release
    - name: Zip executable files
      uses: papeloto/action-zip@v1
      with:
        files: target\release\image_sieve.exe
        dest: image_sieve_Windows_portable.zip
    - name: Archive zip for portable installation
      uses: actions/upload-artifact@v4
      with:
        name: windows-portable
        path: image_sieve_Windows_portable.zip
    - name: Create install package
      run: |
        $env:PATH += ";$env:WIX\bin"
        candle.exe installer\ImageSieve.wxs
        light.exe ImageSieve.wixobj -ext WixUIExtension -cultures:en-us
    - name: Create msix package
      shell: pwsh
      run : |
        $SOURCE_TAG = ${env:GITHUB_REF} -replace ‘refs/tags/v’, ‘’
        if ($SOURCE_TAG -match '\d\d?\.\d\d?\.\d\d?') {
            $version = $SOURCE_TAG + ".0"
        }
        else {
            $version = "0.0.0.0"
        }
        echo "Set version to $version"
        ((Get-Content -path installer\appmanifest.xml -Raw) -replace 'MSIXVERSION',$version) | Set-Content -Path installer\appmanifest_$version.xml
        $sdkToolsPath = Join-Path -Path 'C:\Program Files (x86)\Windows Kits\10\bin' -ChildPath 10.0.26100.0 -AdditionalChildPath x86
        $env:Path += ";$sdkToolsPath"
        & makeappx.exe pack /m installer\appmanifest_$version.xml /f installer\mapping.txt /p ImageSieve.msix
    - name: Signing packages
      if: github.event_name != 'pull_request'
      shell: pwsh
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.PFX_BASE64 }}")
        $currentDirectory = Get-Location
        $certificatePath = Join-Path -Path $currentDirectory -ChildPath "MyCertificate.pfx"
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)
        $sdkToolsPath = Join-Path -Path 'C:\Program Files (x86)\Windows Kits\10\bin' -ChildPath 10.0.26100.0 -AdditionalChildPath x86
        $env:Path += ";$sdkToolsPath"
        SignTool.exe sign /tr http://timestamp.digicert.com /fd SHA256 /a /f "$certificatePath" /p ${{ secrets.PFX_PRIVATE_KEY }} ImageSieve.msi
    - name: Archive install package
      uses: actions/upload-artifact@v4
      with:
        name: windows-installer
        path: ImageSieve.msi
    - name: Archive msix package
      uses: actions/upload-artifact@v4
      with:
        name: windows-msix
        path: ImageSieve.msix
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: ncipollo/release-action@v1
      with:
        artifacts: "*.msix,*.msi,*.zip"
        bodyFile: "CHANGELOG.md"
