name: MSI

on: 
  workflow_dispatch:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-msi:
    
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Create MSI
      run: |
           $env:PATH += ";$env:WIX\bin"
           candle.exe ImageSieve.wxs
           light.exe ImageSieve.wixobj -ext WixUIExtension -cultures:en-us
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: windows-executables
        path: ImageSieve.msi
    - name: Upload windows artifact
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ImageSieve.msi
        asset_name: ImageSieve.msi
        asset_content_type: application/octet-stream
