name: Prepare Ubuntu
on: workflow_call

jobs:
  prepare_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Update apt
        run: sudo apt-get update
      - name: Install deps
        run: sudo apt-get install libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libgtk-3-dev libavcodec-dev libavformat-dev libavutil-dev libswscale-dev
