name: Build

on: 
  push:
    branches:
      - main
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v2
    - name: Install deps
      run: sudo apt-get install libcairo2-dev libjpeg-dev libgif-dev libpango1.0-dev libatk1.0-dev libgtk-3-dev libxcb-shape0-dev libxcb-xfixes0-dev
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test

  build-windows:
    
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build release
      run: cargo build --release
    - uses: papeloto/action-zip@v1
      with:
        files: target/release/image_sieve.exe
        dest: image_sieve_Win.zip
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload windows artifact
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: image_sieve_Win.zip
        asset_name: image_sieve_Win.zip
        asset_content_type: application/zip
