name: Tests

on: 
  push:
    paths-ignore:
      - "*.md"

env:
  CARGO_TERM_COLOR: always

jobs:    
  prepare-ubuntu:
    uses: Futsch1/image-sieve/.github/workflows/prepare_ubuntu.yml@main

  tests-ubuntu:
    runs-on: ubuntu-latest
    needs: prepare-ubuntu
    steps:
    - name: Run tests
      run: cargo test
