name: Tests

on: 
  push:
    paths-ignore:
      - "*.md"

env:
  CARGO_TERM_COLOR: always

jobs:    

  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare_ubuntu
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

  tests-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/prepare_ubuntu
    - name: Install prerequisites
      run: rustup component add llvm-tools-preview
#    - name: Use rust nightly (temp fix because of E0554)
#      run: rustup default nightly
    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov
    - name: Generate code coverage
      env:
        RUST_MIN_STACK: 4000000
      run: cargo test -- --test-threads=1
#      run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info -- --test-threads=1
#    - name: Upload coverage to Codecov
#      uses: codecov/codecov-action@v3
#      with:
#        token: ${{ secrets.CODECOV_TOKEN }}
#        files: lcov.info
#        fail_ci_if_error: true
