name: Tests

on: 
  push:
    paths-ignore:
      - "*.md"

env:
  CARGO_TERM_COLOR: always

jobs:
  prepare-ubuntu:
    - uses: ./.github/workflows/prepare_ubuntu.yml

  tests-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Run tests
      run: cargo test
