name: Tests

on: 
  push:
    paths-ignore:
      - "*.md"

env:
  CARGO_TERM_COLOR: always

jobs:    

  tests-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: Futsch1/image-sieve/.github/workflows/actions/prepare_ubuntu@main
    - name: Run tests
      run: cargo test
